import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { MockProvider } from '@/src/provider/MockProvider'
import QueryProvider from '@/src/provider/QueryProvider'
import Header from '@/src/components/common/header/Header'
import Gnb from '@/src/components/common/gnb/Gnb'

const pretendard = localFont({
  src: '../src/asset/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <QueryProvider>
        <body className={pretendard.className}>
          <MockProvider>
            <Gnb />
            <header className="max-w-[1600px] mx-auto">
              <Header />
            </header>
            {children}
          </MockProvider>
        </body>
      </QueryProvider>
    </html>
  )
}
